### ISSUE TITLE
Codes for Subtask-1 and Subtask-2

### ISSUE THREAD

**Issue by kiucho** [lxchtan/DSTC9-Track1#1]
Thank you for sharing your codes.
By the way, I have a question.
Where can I get codes for Subtask-1 and Subtask-2: detection and selection
I think there's only code for Subtask-3: generation
I would appreciate it if you could point it out if I misunderstood or not.

**Comment by lxchtan** [comment]
Thank you for your interest in our work.
We have no plans to release the codes of the first two subtasks for now.

**Comment by kiucho** [comment]
Ok. Thanks for your answer.
